remote_theme: pages-themes/midnight
plugins:
- jekyll-remote-theme
title: "acodcha's StarCraft Maps"
description: "Maps for the StarCraft Remastered video game by Blizzard Entertainment"
show_downloads: false
